---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: "../../data_bags"   
    run_list:
      - recipe[nace-ckan::database_server]
      - recipe[nace-ckan::solr]
      - recipe[nace_ckan_app::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      ckan:
        db_name: ckan
        db_username: ckan
        db_password: changemenow
